### ISSUE TITLE
 Cannot load library 'lib\libcpu_extension.so': 193 from cwd: D:\freelance\laincy\model-exp-3\OpenVINO-DeeplabV3

### ISSUE THREAD

**Issue by Arham-Aalam** [PINTO0309/OpenVINO-DeeplabV3#1]
**[Required]** Device LaptopPC  
  
**[Required]** device CPU architecture: x86_64  
  
**[Required]** OS : windows  
  
**[Required]** I'm running this command: >python openvino_deeplabv3_test.py -d CPU -pp D:\\freelance\\laincy\\model-exp-3\\OpenVINO-DeeplabV3\\lib  
<br>
<br>
<br>
**[Required]** Error message:  RuntimeError: Cannot load library 'lib\libcpu_extension.so': 193 from cwd: D:\freelance\laincy\model-exp-3\OpenVINO-DeeplabV3
<br>
<br>
<br>
**[Required]** I put the plugin MKLDNNPlugin.dll in lib folder and running the above command but it is unable to read CPU extension. I tried with different paths as well.
Thanks
<br>
<br>
<br>

**Comment by PINTO0309** [comment]
Please try the following article.
The dll you should copy is not "MKLDNNPlugin.dll" but "cpu_extension.dll".
Or "cpu_extension_*.dll".
**https://www.bountysource.com/issues/59287029-intel-inference-engine-cpu_extension_avx2-dll**

**Comment by Arham-Aalam** [comment]
Thanks @PINTO0309 
It worked for me!!
